### ISSUE TITLE
Disk shortage alerts

### ISSUE THREAD

**Issue by ArshamTeymouri** [paritytech/try-runtime-bot#24]
We recently have received some alerts due to the disk space shortage on the try-runtime persistent volume. Following our discussion with @joao-paulo-parity on Matrix, the bot has some methods to handle the disk space shortage itself and it can free up some space when needed.

However, we still receive those alerts until the bot frees up some space! JP recommended to remove the bot from the monitoring entirely, but IMHO there should be a configurable retention policy for the disk where we could set a limit for the disk size instead of removing the bot from monitoring otherwise if the retention policy doesn't work and the application can't handle the disk shortage, we wouldn't know what's wrong with the deployment and a lot of time needs to be spent to troubleshoot the issue.

cc @gabreal

**Comment by joao-paulo-parity** [comment]
> if the retention policy doesn't work and the application can't handle the disk shortage

Handling disk shortage is explicitly part of our strategy, not an afterthought. If this application can't handle disk shortage, it is failing on its purpose and the code needs to be improved. Relying on better monitoring for this is not a solution.

Further, this application will remain operational even with no disk space left because it does not need disk writes to stay responsive.

> we wouldn't know what's wrong with the deployment and a lot of time needs to be spent to troubleshoot the issue

I don't get this at all, aren't the logs available on Grafana? Even the Github comments should have explanation of lacking disk space, e.g. https://github.com/paritytech/substrate/pull/9507#issuecomment-911638973.

> configurable retention policy for the disk

The application's disk grows over time because of accumulating build artifacts. We want to cache build artifacts so that the bot doesn't have to recompile the whole Substrate CLI (takes 2+ hours) every time someone wants to run a command.

If we want to have fine-grained, optimal cache invalidation for build artifacts (while also taking into consideration that we'll constantly be building different branches, each with its own dependencies), it's nevertheless impossible to fully avoid running out of disk space because we're building code from a developer-provided branch and that's out of our control (e.g. the developer could introduce changes which increase the try-runtime CLI's size).

It is possible to be smarter about disk management? Yes. It would take some engineering effort that I am not interested in committing to because cleaning up disk space *when needed* is the simplest and most foolproof solution which also doesn't degrade performance, unlike cache invalidation which has that risk.

The cache invalidation strategy would need to take into account which dependencies are used per-branch and invalidate build artifacts once they are not used in any branch (similar idea to ref-counted memory reclamation) + have time-based heuristics for cleaning up stale artifacts. Clearly that would add complexity and maintenance burden which does not seem worthwhile just so that we can satisfy the alerts.

---

The bottom line is that we handle disk shortage as part of our implementation strategy, thus I am not interested in dealing with alerts of that kind. I do not see the point of implementing a cache invalidation strategy, for all the aforementioned reasons, just so that the alerts can be satisfied; the "wouldn't know what's wrong with the deployment" argument does not seem reasonable - it could be the case if we did not care about disk usage at all, but there's plenty of code for recovering from that scenario + the logs should be available on Grafana in case of errors.

Even if there's an argument for engaging in this cache invalidation implementation, I personally have to work on other tasks and can't offer a commitment for when I'll revisit this, therefore it would be better to disable the alert for now anyways, even if temporarily.

**Comment by gabreal** [comment]
> because cleaning up disk space when needed is the simplest and most foolproof solution
 
everything that can be automated should be as much as possible. there is no reason to include a human dependency for disk space shortages. there is no reason to remove the entire cache. part of the ci runners of the gitlab ci is doing `find /path -atime 2 -delete` on a regular basis in order to avoid disks filling up and manual interventions while still being able to make use of previous build artefacts. would you be able to implement something like that?


> Even the Github comments should have explanation of lacking disk space, e.g. paritytech/substrate#9507 (comment).

Alerts can certainly be silenced temporarily, but this is not about satisfying certain alerts. It's about creating an infrastructure that is less frustrating for ppl using it. if ppl have to ask around why some component isn't working anymore, that is just annoying.


> Relying on better monitoring for this is not a solution.

yes, it is :) how would your app handle failed builds due to disk space shortage, who would interpret errors and troubleshoot this? even the best manual in case of your absence cannot replace this simple automation.

**Comment by joao-paulo-parity** [comment]
> everything that can be automated should be as much as possible. there is no reason to include a human dependency for disk space shortages.

All of the disk cleanup strategies I mentioned are implemented directly in code and executed automatically when the problem is found.

https://github.com/paritytech/try-runtime-bot/blob/f9a612c67978aea4dd7bda036a44f9e78709489b/src/executor.ts#L157

There's no need for someone to intervene, at any point, because the program should recover from the problem by itself during execution.

> how would your app handle failed builds due to disk space shortage, who would interpret errors and troubleshoot this?

It is able to handle disk space shortage because handling it is part of the implementation. No developer needs to interpret anything for the disk space usage problem to be handled.

*If our handling code is bugged* and the application is failing to recover for that reason, given that recovering is explicitly in its strategy and should be solved automatically, without intervention, through code, then a developer would have to fix the code, not intervene manually.

> part of the ci runners of the gitlab ci is doing find /path -atime 2 -delete on a regular basis in order to avoid disks filling up and manual interventions while still being able to make use of previous build artefacts. would you be able to implement something like that?

It would be possible to implement a recurrent procedure for cleaning up stale artifacts, in fact we already have an issue for that: https://github.com/paritytech/try-runtime-bot/issues/14. While it should be implemented at some point, it wasn't so far for the following reasons:

- It's not strictly necessary at the moment.
- The disk shortage problem is ultimately out of our control since we build arbitrary code on whatever branch the developer provides.
- Invalidating artifacts naively incurs performance costs which are worse than having to deal with this problem. A good algorithm has to be designed, implemented, tested, etc.
- It's not a high priority for me because I have to work on something else.

**Comment by gabreal** [comment]
Ah, thanks for the clarification, wasn't aware there was a disk space error handling in the code.

Do i understand correctly that your code removes [all of the build artifacts of a project](https://github.com/paritytech/try-runtime-bot/blob/f9a612c67978aea4dd7bda036a44f9e78709489b/src/utils.ts#L329) when the disk is full? If yes, then using the `find` command which checks if build artifacts haven't been accessed for some time seems to be more efficient to me. Jobs would not have to fail first (and require extra time to compile) and old artifacts will not be used anymore anyways. I don't think it has to be more sophisticated than that esp given that this is also how the ci is caching artifacts currently (even the redis build cache is using LRU retention).

**Comment by joao-paulo-parity** [comment]
If a project fails due to no disk space, first it will try to clean up other projects:

https://github.com/paritytech/try-runtime-bot/blob/f9a612c67978aea4dd7bda036a44f9e78709489b/src/executor.ts#L189

If that also fails, the project will try to clean up itself:

https://github.com/paritytech/try-runtime-bot/blob/f9a612c67978aea4dd7bda036a44f9e78709489b/src/executor.ts#L212

We can add several fine-grained steps in-between and be smarter in general, as mentioned several times, but that's not the reason why I suggested disabling the disk shortage alerts.

For me, as a developer, alerts serve the purpose of signaling that someone needs to take action on their behalf. For this application, disk shortage does not conform to that expectation because it's something that can eventually happen, for whatever reason (since we're building whatever code the developer provides) without the application being broken; the program does not ultimately need disk writes in order to report errors. If it would fail from recovering from those kind of failures, we would know:

https://github.com/paritytech/try-runtime-bot/blob/f9a612c67978aea4dd7bda036a44f9e78709489b/src/executor.ts#L231

Even if you would double the disk space we have right now, the alerts would still be reported even though there's no problem with the application, so I don't see a point in having them. Increasing the disk space might be *useful* so that we don't hit the limits often, because when that happens we have to nuke the cached artifacts and that incurs a performance hit since it'll take longer to build the Substrate CLI again. However, even if there's more disk space, it does not matter because the alerts would still be representative of a "problem" that is not really a problem.

I have not prioritized implementing https://github.com/paritytech/try-runtime-bot/issues/14 so far and can't prioritize it in the near future. Bear in mind that, given that disk space is a limited resource, even if sane *pre-emptive* measures like cleaning stale artifacts were to be implemented, disk space shortage alerts would still not be useful because recovering from this failure is something that happens automatically and the logs would tell if the mechanism is broken.

**Comment by joao-paulo-parity** [comment]
After https://github.com/paritytech/try-runtime-bot/pull/57 we should no longer have to deal with lack of disk space in the bot's host since the commands would be executed on GitLab CI
